Feature/KX-110: fix scale according to cards backend
GiuseppeArbore/polito-se2-24-Kiruna-eXplorer-18 pull request #78
Opened 2024-12-09 16:32 UTC by dlste

⚠️ THIS PR CHANGES THE DATABASE FORMAT ⚠️

Please reset you local db or update it to be compliant with the new format

2024-12-09 20:20 UTC, GiuseppeArbore approved these changes

2024-12-11 09:27 UTC, golnazsaraji requested changes

2024-12-11 09:27 UTC, golnazsaraji commented on client/src/components/documents/Document.tsx
> +import { AreaType, KxDocumentType, ScaleType, Stakeholders } from "../../enum";
<img width="1440" alt="Screen Shot 2024-12-11 at 10 23 16" src="https://github.com/user-attachments/assets/73b654b2-2bbf-4f29-a4a4-36d108c08230">
by clicking a document on the map, and redirecting to the details, the page becomes blank.

2024-12-11 15:05 UTC, lbordino approved these changes

2024-12-12 12:04 UTC, merged